name: traff_att_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  excel: ^4.0.6
  path_provider: ^2.1.5
  open_filex: ^4.3.2 


  
  url_launcher: ^6.3.0 
  fl_chart: ^1.0.0
  device_info_plus: ^10.1.0
  crypto: ^3.0.3
  dropdown_search: ^6.0.2
  screenshot: ^3.0.0
  syncfusion_flutter_xlsio: ^29.2.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg
    - assets/images/web_pattern.png